version: '3'

volumes:
  db-data:
    driver: local
  shop:
    driver: local

services:
  database:
    image: mariadb:10.10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: prestashop
      MARIADB_DATABASE: prestashop
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3


  db-admin:
    image: phpmyadmin
    ports:
      - "33031:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: prestashop
      PMA_PMADB: phpmyadmin
    restart: always
    depends_on:
      - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3


  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    environment:
      PRESTASHOP_DATABASE_HOST: database
      PRESTASHOP_DATABASE_NAME: prestashop
      PRESTASHOP_DATABASE_USER: root
      PRESTASHOP_DATABASE_PASSWORD: prestashop
      PRESTASHOP_ENABLE_HTTPS: 1
      PRESTASHOP_SMTP_HOST: smtp.gmail.com
      PRESTASHOP_SMTP_PORT: 465
      PRESTASHOP_SMTP_USER: squeezleys
      PRESTASHOP_SMTP_PASSWORD: $SMTP_PASSWORD
      PRESTASHOP_LANGUAGE: pl
      PRESTASHOP_COUNTRY: pl
      PRESTASHOP_FIRST_NAME: Lukasz
      PRESTASHOP_LAST_NAME: Milewski
      PRESTASHOP_EMAIL: squeezleys@gmail.com
      PRESTASHOP_PASSWORD: $ADMIN_PASSWORD
    ports:
      - "33030:8080"
      - "33033:8443"
    volumes:
      - ./preinstall:/tmp/pre-install-scripts
    restart: always
    depends_on:
      - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3


  image-server:
    image: httpd
    volumes:
      - ../data/images/:/usr/local/apache2/htdocs/
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
      restart_policy:
        condition: on-failure
        max_attempts: 3
