version: '3'

volumes:
  db-data:
    driver: local
  shop:
    driver: local

services:
  database:
    image: mariadb:10.10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: prestashop
      MARIADB_DATABASE: prestashop
    restart: always

  db-admin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: prestashop
      PMA_PMADB: phpmyadmin
    restart: always
    depends_on:
      - database

  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    environment:
      PRESTASHOP_DATABASE_HOST: database
      PRESTASHOP_DATABASE_NAME: prestashop
      PRESTASHOP_DATABASE_USER: root
      PRESTASHOP_DATABASE_PASSWORD: prestashop
      PRESTASHOP_ENABLE_HTTPS: yes
      PRESTASHOP_SMTP_HOST: smtp.gmail.com
      PRESTASHOP_SMTP_PORT: 587
      PRESTASHOP_SMTP_USER: squeezleys@gmail.com
      PRESTASHOP_SMTP_PASSWORD: $SMTP_PASSOWRD
      PRESTASHOP_LANGUAGE: pl
      PRESTASHOP_COUNTRY: pl
      PRESTASHOP_FIRST_NAME: Lukasz
      PRESTASHOP_LAST_NAME: Milewski
      PRESTASHOP_EMAIL: squeezleys@gmail.com
      PRESTASHOP_PASSWORD: $ADMIN_PASSWORD
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - shop:/var/www/html:delegated
      - ../data/images:/var/www/html/images:cached
      - ./preinstall:/tmp/pre-install-scripts
    restart: always
    depends_on:
      - database
