version: '3'

volumes:
  db-data:
  var:
  shop:

services:
  database:
    image: mariadb:10.10
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: prestashop
      MARIADB_DATABASE: prestashop
    restart: always

  
  db-admin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: prestashop
      PMA_PMADB: phpmyadmin
    restart: always
    depends_on:
      - database

  prestashop:
    image: prestashop/prestashop:1.7
    environment:
      DB_SERVER: database
      DB_NAME: prestashop
      DB_PASSWD: prestashop
      #PS_INSTALL_DB: 1
      PS_LANGUAGE: "pl"
      PS_COUNTRY: "PL"
      ADMIN_MAIL:
      ADMIN_PASSWD: 
      PS_DOMAIN: localhost:8001
    ports:
      - "8080:80"
    volumes:
      - shop:/var/www/html:delegated
    restart: always
    depends_on:
      - database